# Generated by Django 4.2 on 2023-04-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Math_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_task', models.IntegerField()),
                ('condition', models.TextField()),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Math_theory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_theory', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('condition', models.TextField()),
            ],
        ),
    ]
