version: "3"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    links:
      - web
      - vue
    depends_on:
      - web
      - vue
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
  web:
    container_name: web
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
            gunicorn deploy_humanhack.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8077:8077"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
  vue:
    container_name: vue
    build: ./Vue_app_deploy
    ports:
      - "5173:5173"
volumes:
  media_volume:
  static_volume: